ChannelRemoval; %1
Classic %5
ColorReduction %1
ColorShift %1
ColorspaceChange %1
ColorVariation %1
ContentFill %1
DCT %1
Deconvolution %1
DecorrStretch %1
Deformation %1
Dehaze %1
DenoiseMF2 %1
DenoiseWDC %1
Dithering %1
FFT %1
FFT_2 %1
FFTCombine %1
Hampel %1
HilbertTransform  %1
Histeq  %1
Laplacian  %3
Negative  %1
Pixelate %1
PixelShuffle %1
PolarDecomposition %1
Project %1
SingValDec %1
SuperPixel %1
Vignetting %1